#:import Clock kivy.clock.Clock

<ChipsScreen>:
    name: "chips_screen"

    MDBackTopBar:
        id: chips_top_bar

        MDWhiteTopAppBarTitle:
            text: "Микросхемы и компоненты"

    ScrollView:
        size_hint_y: (root.height - sp(60)) / root.height
        pos_hint: {"top": (root.height - chips_top_bar.height) / root.height}

        MDPaddedList:

            MDIconCard:
                on_release: root.manager.current = "chips_analogs_select_screen"

                ImageButton:
                    source: "media/chips_analogs.png"
                    on_release: root.manager.current = "chips_analogs_select_screen"

                MDShortenLabel:
                    text: "Аналоги отечественных микросхем"

<ChipsAnalogsSelectScreen>:
    name: "chips_analogs_select_screen"

    MDBackTopBar:
        id: chips_analogs_select_top_bar

        MDWhiteTopAppBarTitle:
            text: "Аналоги отечественных микросхем"

    ScrollView:
        size_hint_y: (root.height - sp(60)) / root.height
        pos_hint: {"top": (root.height - chips_analogs_select_top_bar.height) / root.height}

        MDPaddedList:
        
            MDIconCard:
                on_release: 
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series133",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 133"

                ImageButton:
                    source: "media/series133.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 133"

            MDIconCard:
                on_release: 
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series140",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 140"

                ImageButton:
                    source: "media/series140.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 140"

            MDIconCard:
                on_release: 
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series142",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 142"

                ImageButton:
                    source: "media/series142.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 142"

            MDIconCard:
                on_release: 
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series153",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 153"

                ImageButton:
                    source: "media/series153.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 153"

            MDIconCard:
                on_release: 
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series154",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 154"

                ImageButton:
                    source: "media/series154.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 154"

            MDIconCard:
                on_release: 
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series155",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 155"

                ImageButton:
                    source: "media/series155.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 155"

            MDIconCard:
                on_release: 
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series157",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 157"

                ImageButton:
                    source: "media/series157.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 157"

            MDIconCard:
                on_release: 
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series169",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 169"

                ImageButton:
                    source: "media/series169.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 169"

            MDIconCard:
                on_release: 
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series170",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 170"

                ImageButton:
                    source: "media/series170.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 170"

            MDIconCard:
                on_release: 
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series171",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 171"

                ImageButton:
                    source: "media/series171.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 171"

            MDIconCard:
                on_release: 
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series174",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 174"

                ImageButton:
                    source: "media/series174.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 174"

            MDIconCard:
                on_release: 
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series175",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 175"

                ImageButton:
                    source: "media/series175.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 175"

            MDIconCard:
                on_release: 
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series176",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 176"

                ImageButton:
                    source: "media/series176.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 176"

            MDIconCard:
                on_release: 
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series193",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 193"

                ImageButton:
                    source: "media/series193.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 193"

            MDIconCard:
                on_release: 
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series198",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 198"

                ImageButton:
                    source: "media/series198.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 198"

            MDIconCard:
                on_release: 
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series249",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 249"

                ImageButton:
                    source: "media/series249.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 249"

            MDIconCard:
                on_release: 
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series427",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 427"

                ImageButton:
                    source: "media/series427.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 427"

            MDIconCard:
                on_release: 
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series490",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 490"

                ImageButton:
                    source: "media/series490.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 490"

            MDIconCard:
                on_release: 
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series511",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 511"

                ImageButton:
                    source: "media/series511.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 511"

            MDIconCard:
                on_release: 
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series512",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 512"

                ImageButton:
                    source: "media/series512.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 512"

            MDIconCard:
                on_release: 
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series514",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 514"

                ImageButton:
                    source: "media/series514.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 514"

            MDIconCard:
                on_release: 
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series521",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 521"

                ImageButton:
                    source: "media/series521.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 521"

            MDIconCard:
                on_release: 
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series522",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 522"

                ImageButton:
                    source: "media/series522.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 522"

            MDIconCard:
                on_release: 
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series525",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 525"

                ImageButton:
                    source: "media/series525.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 525"

            MDIconCard:
                on_release: 
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series526",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 526"

                ImageButton:
                    source: "media/series526.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 526"

            MDIconCard:
                on_release: 
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series528",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 528"

                ImageButton:
                    source: "media/series528.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 528"

            MDIconCard:
                on_release: 
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series529",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 529"

                ImageButton:
                    source: "media/series529.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 529"

            MDIconCard:
                on_release: 
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series530",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 530"

                ImageButton:
                    source: "media/series530.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 530"

            MDIconCard:
                on_release: 
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series531",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 531"

                ImageButton:
                    source: "media/series531.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 531"

            MDIconCard:
                on_release: 
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series533",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 533"

                ImageButton:
                    source: "media/series533.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 533"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series537",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 537"

                ImageButton:
                    source: "media/series537.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 537"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series538",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 538"

                ImageButton:
                    source: "media/series538.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 538"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series541",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 541"

                ImageButton:
                    source: "media/series541.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 541"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series543",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 543"

                ImageButton:
                    source: "media/series543.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 543"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series544",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 544"

                ImageButton:
                    source: "media/series544.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 544"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series548",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 548"

                ImageButton:
                    source: "media/series548.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 548"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series551",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 551"

                ImageButton:
                    source: "media/series551.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 551"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series553",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 553"

                ImageButton:
                    source: "media/series553.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 553"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series554",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 554"

                ImageButton:
                    source: "media/series554.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 554"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series555",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 555"

                ImageButton:
                    source: "media/series555.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 555"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series556",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 556"

                ImageButton:
                    source: "media/series556.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 556"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series558",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 558"

                ImageButton:
                    source: "media/series558.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 558"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series559",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 559"

                ImageButton:
                    source: "media/series559.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 559"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series561",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 561"

                ImageButton:
                    source: "media/series561.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 561"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series563",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 563"

                ImageButton:
                    source: "media/series563.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 563"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series564",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 564"

                ImageButton:
                    source: "media/series564.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 564"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series565",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 565"

                ImageButton:
                    source: "media/series565.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 565"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series568",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 568"

                ImageButton:
                    source: "media/series_noname.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 568"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series571",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 571"

                ImageButton:
                    source: "media/series571.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 571"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series572",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 572"

                ImageButton:
                    source: "media/series572.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 572"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series573",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 573"

                ImageButton:
                    source: "media/series573.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 573"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series574",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 574"

                ImageButton:
                    source: "media/series574.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 574"

            MDIconCard:
                on_release: 
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series580",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 580"

                ImageButton:
                    source: "media/series580.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 580"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series585",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 585"

                ImageButton:
                    source: "media/series585.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 585"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series588",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 588"

                ImageButton:
                    source: "media/series588.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 588"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series589",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 589"

                ImageButton:
                    source: "media/series589.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 589"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series590",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 590"

                ImageButton:
                    source: "media/series590.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 590"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series591",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 591"

                ImageButton:
                    source: "media/series591.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 591"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series593",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 593"

                ImageButton:
                    source: "media/series593.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 593"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series594",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 594"

                ImageButton:
                    source: "media/series594.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 594"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series597",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 597"

                ImageButton:
                    source: "media/series597.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 597"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1002",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1002"

                ImageButton:
                    source: "media/series1002.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1002"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1004",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1004"

                ImageButton:
                    source: "media/series1004.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1004"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1005",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1005"

                ImageButton:
                    source: "media/series1005.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1005"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1006",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1006"

                ImageButton:
                    source: "media/series1006.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1006"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1008",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1008"

                ImageButton:
                    source: "media/series1008.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1008"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1009",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1009"

                ImageButton:
                    source: "media/series1009.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1009"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1014",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1014"

                ImageButton:
                    source: "media/series1014.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1014"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1015",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1015"

                ImageButton:
                    source: "media/series1015.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1015"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1016",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1016"

                ImageButton:
                    source: "media/series1016.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1016"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1017",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1017"

                ImageButton:
                    source: "media/series1017.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1017"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1019",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1019"

                ImageButton:
                    source: "media/series1019.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1019"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1021",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1021"

                ImageButton:
                    source: "media/series1021.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1021"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1022",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1022"

                ImageButton:
                    source: "media/series1022.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1022"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1023",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1023"

                ImageButton:
                    source: "media/series1023.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1023"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1025",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1025"

                ImageButton:
                    source: "media/series1025.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1025"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1026",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1026"

                ImageButton:
                    source: "media/series1026.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1026"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1027",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1027"

                ImageButton:
                    source: "media/series1027.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1027"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1031",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1031"

                ImageButton:
                    source: "media/series_noname.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1031"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1032",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1032"

                ImageButton:
                    source: "media/series1032.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1032"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1033",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1033"

                ImageButton:
                    source: "media/series1033.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1033"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1038",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1038"

                ImageButton:
                    source: "media/series1038.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1038"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1039",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1039"

                ImageButton:
                    source: "media/series1039.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1039"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1040",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1040"

                ImageButton:
                    source: "media/series1040.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1040"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1043",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1043"

                ImageButton:
                    source: "media/series1043.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1043"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1051",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1051"

                ImageButton:
                    source: "media/series1051.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1051"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1053",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1053"

                ImageButton:
                    source: "media/series1053.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1053"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1054",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1054"

                ImageButton:
                    source: "media/series1054.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1054"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1055",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1055"

                ImageButton:
                    source: "media/series1055.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1055"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1056",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1056"

                ImageButton:
                    source: "media/series1056.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1056"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1057",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1057"

                ImageButton:
                    source: "media/series1057.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1057"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1058",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1058"

                ImageButton:
                    source: "media/series1058.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1058"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1064",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1064"

                ImageButton:
                    source: "media/series1064.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1064"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1066",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1066"

                ImageButton:
                    source: "media/series1066.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1066"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1071",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1071"

                ImageButton:
                    source: "media/series1071.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1071"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1072",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1072"

                ImageButton:
                    source: "media/series1072.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1072"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1075",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1075"

                ImageButton:
                    source: "media/series1075.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1075"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1082",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1082"

                ImageButton:
                    source: "media/series1082.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1082"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1084",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1084"

                ImageButton:
                    source: "media/series1084.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1084"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1086",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1086"

                ImageButton:
                    source: "media/series1086.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1086"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1087",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1087"

                ImageButton:
                    source: "media/series1087.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1087"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1091",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1091"

                ImageButton:
                    source: "media/series1091.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1091"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1100",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1100"

                ImageButton:
                    source: "media/series1100.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1100"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1102",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1102"

                ImageButton:
                    source: "media/series1102.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1102"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1103",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1103"

                ImageButton:
                    source: "media/series1103.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1103"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1107",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1107"

                ImageButton:
                    source: "media/series1107.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1107"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1108",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1108"

                ImageButton:
                    source: "media/series1108.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1108"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1109",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1109"

                ImageButton:
                    source: "media/series1109.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1109"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1113",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1113"

                ImageButton:
                    source: "media/series1113.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1113"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1114",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1114"

                ImageButton:
                    source: "media/series1114.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1114"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1116",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1116"

                ImageButton:
                    source: "media/series1116.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1116"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1118",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1118"

                ImageButton:
                    source: "media/series1118.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1118"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1121",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1121"

                ImageButton:
                    source: "media/series1121.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1121"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1125",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1125"

                ImageButton:
                    source: "media/series1125.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1125"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1128",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1128"

                ImageButton:
                    source: "media/series1128.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1128"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1146",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1146"

                ImageButton:
                    source: "media/series1146.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1146"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1152",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1152"

                ImageButton:
                    source: "media/series1152.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1152"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1156",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1156"

                ImageButton:
                    source: "media/series1156.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1156"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1157",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1157"

                ImageButton:
                    source: "media/series1157.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1157"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1162",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1162"

                ImageButton:
                    source: "media/series1162.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1162"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1167",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1167"

                ImageButton:
                    source: "media/series1167.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1167"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1183",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1183"

                ImageButton:
                    source: "media/series1183.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1183"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1401",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1401"

                ImageButton:
                    source: "media/series1401.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1401"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1407",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1407"

                ImageButton:
                    source: "media/series1407.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1407"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1408",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1408"

                ImageButton:
                    source: "media/series1408.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1408"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1409",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1409"

                ImageButton:
                    source: "media/series1409.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1409"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1413",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1413"

                ImageButton:
                    source: "media/series1413.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1413"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1420",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1420"

                ImageButton:
                    source: "media/series1420.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1420"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1422",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1422"

                ImageButton:
                    source: "media/series1422.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1422"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1423",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1423"

                ImageButton:
                    source: "media/series1423.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1423"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1426",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1426"

                ImageButton:
                    source: "media/series1426.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1426"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1433",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1433"

                ImageButton:
                    source: "media/series1433.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1433"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1435",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1435"

                ImageButton:
                    source: "media/series1435.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1435"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1436",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1436"

                ImageButton:
                    source: "media/series1436.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1436"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1500",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1500"

                ImageButton:
                    source: "media/series1500.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1500"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1506",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1506"

                ImageButton:
                    source: "media/series1506.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1506"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1507",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1507"

                ImageButton:
                    source: "media/series1507.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1507"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1520",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1520"

                ImageButton:
                    source: "media/series1520.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1520"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1521",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1521"

                ImageButton:
                    source: "media/series1521.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1521"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1526",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1526"

                ImageButton:
                    source: "media/series1526.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1526"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1531",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1531"

                ImageButton:
                    source: "media/series1531.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1531"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1533",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1533"

                ImageButton:
                    source: "media/series1533.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1533"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1540",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1540"

                ImageButton:
                    source: "media/series1540.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1540"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1554",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1554"

                ImageButton:
                    source: "media/series1554.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1554"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1556",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1556"

                ImageButton:
                    source: "media/series1556.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1556"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1561",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1561"

                ImageButton:
                    source: "media/series1561.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1561"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1564",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1564"

                ImageButton:
                    source: "media/series1564.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1564"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1566",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1566"

                ImageButton:
                    source: "media/series1566.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1566"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1568",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1568"

                ImageButton:
                    source: "media/series1568.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1568"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1590",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1590"

                ImageButton:
                    source: "media/series1590.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1590"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1601",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1601"

                ImageButton:
                    source: "media/series1601.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1601"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1603",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1603"

                ImageButton:
                    source: "media/series1603.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1603"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1617",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1617"

                ImageButton:
                    source: "media/series1617.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1617"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1623",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1623"

                ImageButton:
                    source: "media/series1623.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1623"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1625",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1625"

                ImageButton:
                    source: "media/series1625.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1625"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1628",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1628"

                ImageButton:
                    source: "media/series1628.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1628"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1630",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1630"

                ImageButton:
                    source: "media/series1630.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1630"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1656",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1656"

                ImageButton:
                    source: "media/series1656.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1656"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1800",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1800"

                ImageButton:
                    source: "media/series1800.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1800"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1802",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1802"

                ImageButton:
                    source: "media/series1802.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1802"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1809",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1809"

                ImageButton:
                    source: "media/series1809.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1809"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1810",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1810"

                ImageButton:
                    source: "media/series1810.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1810"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1816",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1816"

                ImageButton:
                    source: "media/series1816.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1816"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1818",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1818"

                ImageButton:
                    source: "media/series1818.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1818"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1820",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1820"

                ImageButton:
                    source: "media/series1820.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1820"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1821",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1821"

                ImageButton:
                    source: "media/series1821.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1821"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1823",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1823"

                ImageButton:
                    source: "media/series1823.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1823"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1827",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1827"

                ImageButton:
                    source: "media/series1827.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1827"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1830",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1830"

                ImageButton:
                    source: "media/series1830.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1830"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1834",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1834"

                ImageButton:
                    source: "media/series1834.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1834"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1835",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1835"

                ImageButton:
                    source: "media/series1835.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1835"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1843",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1843"

                ImageButton:
                    source: "media/series1843.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1843"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1850",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1850"

                ImageButton:
                    source: "media/series1850.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1850"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1852",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1852"

                ImageButton:
                    source: "media/series1852.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1852"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1853",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1853"

                ImageButton:
                    source: "media/series1853.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1853"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1858",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1858"

                ImageButton:
                    source: "media/series1858.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1858"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series1873",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия 1873"

                ImageButton:
                    source: "media/series1873.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия 1873"

            MDIconCard:
                on_release:
                    root.manager.current = "chips_analogs_screen"; \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs.build_table("series_ipv",
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_scroll_view); \
                    root.manager.get_screen("chips_analogs_screen").ids.chips_analogs_top_bar_title.text = "Серия ИПВ"

                ImageButton:
                    source: "media/series_ipv.png"
                    on_release: root.manager.current = "chips_analogs_screen"

                MDShortenLabel:
                    text: "Серия ИПВ"

<ChipsAnalogsScreen>:
    name: "chips_analogs_screen"

    MDBackTopBar:
        id: chips_analogs_top_bar

        MDWhiteTopAppBarTitle:
            id: chips_analogs_top_bar_title
            text: "Test"

    ScrollView:
        id: chips_analogs_scroll_view
        size_hint_y: (root.height - sp(60)) / root.height
        pos_hint: {"top": (root.height - chips_analogs_top_bar.height) / root.height}
        do_scroll_x: False

        ChipsAnalogs:
            id: chips_analogs
